apiVersion: v1
kind: Service
metadata:
  name: demo-app-nodeport
  namespace: demo-app
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Maps to Kind cluster port mapping
    protocol: TCP
  selector:
    app: demo-app
