apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app-config
  namespace: default
data:
  message: "Hello from ArgoCD GitOps!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: simple-app-config
              key: message
