# Kind Multi-Node Cluster Configuration for GitOps Demo
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev

# Configure the cluster
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  
  # Disable default CNI to allow installation of custom CNI (Cilium/Calico)
  disableDefaultCNI: false
  
  # Configure pod and service subnets
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

# Define cluster nodes
nodes:
  # Control plane node
  - role: control-plane
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Expose port 80 for ingress controller
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # Expose port 443 for ingress controller
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # Expose port 30000-32767 for NodePort services
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # ArgoCD Server NodePort
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
    extraMounts:
      # Mount local directory for persistent storage
      - hostPath: /tmp/kind-dev-storage
        containerPath: /tmp/hostpath-provisioner
        
  # Worker node 1
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-type=worker"
    extraMounts:
      - hostPath: /tmp/kind-dev-storage
        containerPath: /tmp/hostpath-provisioner

  # Worker node 2
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-type=worker"
    extraMounts:
      - hostPath: /tmp/kind-dev-storage
        containerPath: /tmp/hostpath-provisioner

# Configure feature gates and runtime config
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
  - |
    kind: KubeProxyConfiguration
    metricsBindAddress: 0.0.0.0
