kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev
nodes:
- role: control-plane
  image: kindest/node:v1.31.0
  extraPortMappings:
  # ArgoCD ports
  - containerPort: 30080
    hostPort: 9080
    protocol: TCP
  - containerPort: 30443
    hostPort: 9443
    protocol: TCP
  # Ingress Controller ports (NodePort mappings)
  - containerPort: 30269
    hostPort: 8080
    protocol: TCP
  - containerPort: 31186
    hostPort: 8443
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  image: kindest/node:v1.31.0
