# Kind cluster configuration for GitOps development
# This creates a multi-node cluster optimized for ArgoCD and GitOps workflows

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev

# Use stable Kubernetes version (1.31.0 is more stable than 1.33.1)
nodes:
- role: control-plane
  image: kindest/node:v1.31.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # ArgoCD Server
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  # ArgoCD Server HTTPS
  - containerPort: 30443
    hostPort: 8443
    protocol: TCP
  # HTTP Ingress
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # HTTPS Ingress
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # Grafana
  - containerPort: 30300
    hostPort: 3000
    protocol: TCP
  # Prometheus
  - containerPort: 30900
    hostPort: 9090
    protocol: TCP

# Worker nodes for application workloads
- role: worker
  image: kindest/node:v1.31.0
  labels:
    workload-type: "applications"

- role: worker
  image: kindest/node:v1.31.0
  labels:
    workload-type: "monitoring"

# Networking configuration
networking:
  # Disable default CNI to allow custom installation
  disableDefaultCNI: false
  # Pod subnet
  podSubnet: "10.244.0.0/16"
  # Service subnet
  serviceSubnet: "10.96.0.0/16"

# Feature gates for advanced Kubernetes features
featureGates:
  # Enable ServerSideApply for better GitOps experience
  ServerSideApply: true
  # Enable EphemeralContainers for debugging
  EphemeralContainers: true
