# Kind cluster configuration for GitOps development
# This creates a multi-node cluster optimized for ArgoCD and GitOps workflows

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev

# Use stable Kubernetes version (1.31.0 is more stable than 1.33.1)
nodes:
- role: control-plane
  image: kindest/node:v1.31.0
  extraPortMappings:
  # ArgoCD ports
  - containerPort: 30080
    hostPort: 9080
    protocol: TCP
  - containerPort: 30443
    hostPort: 9443
    protocol: TCP
  # Ingress Controller ports (NodePort mappings)
  - containerPort: 30269
    hostPort: 8080
    protocol: TCP
  - containerPort: 31186
    hostPort: 8443
    protocol: TCP
  # Monitoring ports (Grafana)
  - containerPort: 32000
    hostPort: 3000
    protocol: TCP
  # Monitoring ports (Prometheus)
  - containerPort: 32090
    hostPort: 9090
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
  - |
    kind: KubeProxyConfiguration
    metricsBindAddress: 0.0.0.0

# Worker nodes for application workloads
- role: worker
  image: kindest/node:v1.31.0
  labels:
    workload-type: "applications"

- role: worker
  image: kindest/node:v1.31.0
  labels:
    workload-type: "monitoring"

# Networking configuration
networking:
  # Disable default CNI to allow custom installation
  disableDefaultCNI: false
  # Pod subnet
  podSubnet: "10.244.0.0/16"
  # Service subnet
  serviceSubnet: "10.96.0.0/16"

# Feature gates for advanced Kubernetes features
featureGates:
  # Enable ServerSideApply for better GitOps experience
  ServerSideApply: true
  # Enable EphemeralContainers for debugging
  EphemeralContainers: true
