apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: argocd-metrics
    app.kubernetes.io/part-of: argocd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
spec:
  type: ClusterIP
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: metrics
  selector:
    app.kubernetes.io/name: argocd-application-controller
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server-metrics
    app.kubernetes.io/part-of: argocd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
spec:
  type: ClusterIP
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
    name: metrics
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server-metrics
    app.kubernetes.io/part-of: argocd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8084"
spec:
  type: ClusterIP
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
    name: metrics
  selector:
    app.kubernetes.io/name: argocd-repo-server
