apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-app
  labels:
    app: demo-web-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>GitOps Demo Application</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 40px;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                min-height: 100vh;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
            .container {
                text-align: center;
                background: rgba(255, 255, 255, 0.1);
                padding: 40px;
                border-radius: 10px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            }
            h1 {
                font-size: 3em;
                margin-bottom: 20px;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
            }
            .info {
                font-size: 1.2em;
                margin: 20px 0;
                opacity: 0.9;
            }
            .status {
                background: rgba(76, 175, 80, 0.8);
                padding: 10px 20px;
                border-radius: 5px;
                margin: 20px 0;
                font-weight: bold;
            }
            .footer {
                margin-top: 30px;
                font-size: 0.9em;
                opacity: 0.7;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 GitOps Demo App</h1>
            <div class="status">✅ Deployed via ArgoCD GitOps</div>
            <div class="info">
                <p>📦 <strong>Repository:</strong> pyzons/gitops-demo-app</p>
                <p>🔄 <strong>Managed by:</strong> ArgoCD</p>
                <p>☸️ <strong>Cluster:</strong> Kind Development</p>
                <p>🏷️ <strong>Version:</strong> v1.0.0</p>
            </div>
            <div class="footer">
                <p>Powered by Kubernetes + ArgoCD + GitOps</p>
                <p>🌐 Accessible via NodePort 30080</p>
            </div>
        </div>
    </body>
    </html>
