apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: demo-app-kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: demo-web-app
  app.kubernetes.io/instance: demo-app-gitops
  app.kubernetes.io/managed-by: argocd

images:
  - name: nginx
    newTag: "1.21"
