apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: demo-app
        env:
        - name: ENVIRONMENT
          value: "development"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
